import time
import uuid

from logger import log_info


class SessionEvents:
    """Constants for session event types that connections can subscribe to."""

    AUDIO = "audio"
    VIDEO = "video"
    MESSAGE = "message"


class Session:
    """A group of connections sharing the same media/data events.

    Every connection is attached to a session when it is created. Media
    received on a connection (or generated by one of its models) and data
    channel messages are published to the session, and every other attached
    connection receives them, so additional participants can watch and
    participate in the same session."""

    def __init__(self):
        self.id = str(uuid.uuid4())
        self.created_at = time.time()
        self.connections = []

    def attach(self, connection):
        """Attach a connection to this session."""
        if connection not in self.connections:
            self.connections.append(connection)
            connection.session = self
            log_info(
                f"Connection {connection.id} attached to session ({len(self.connections)} connections)", context=self.id
            )

    def detach(self, connection):
        """Detach a connection. The session is destroyed once it has no connections."""
        if connection in self.connections:
            self.connections.remove(connection)
            log_info(
                f"Connection {connection.id} detached from session ({len(self.connections)} connections)",
                context=self.id,
            )
        if connection.session is self:
            connection.session = None
        if not self.connections:
            SessionManager().remove_session(self)

    def has_subscribers(self, source=None) -> bool:
        """True when at least one connection other than `source` is attached."""
        return any(conn is not source for conn in self.connections)

    def publish(self, event_type, data, source=None):
        """Deliver an event to every attached connection except `source`."""
        for conn in list(self.connections):
            if conn is source:
                continue
            try:
                conn.handle_session_event(event_type, data, source)
            except Exception as e:
                log_info(f"Error delivering session event {event_type} to {conn.id}: {e}", context=self.id)


class SessionManager:
    """Keeps track of all running sessions. Singleton pattern."""

    _instance = None

    def __new__(cls):
        if cls._instance is None:
            cls._instance = super().__new__(cls)
            cls._instance.sessions = {}
        return cls._instance

    def create_session(self) -> Session:
        session = Session()
        self.sessions[session.id] = session
        log_info("Session created", context=session.id)
        return session

    def find_session_by_id(self, session_id):
        if not session_id:
            return None
        return self.sessions.get(session_id)

    def remove_session(self, session):
        if self.sessions.pop(session.id, None):
            log_info("Session destroyed", context=session.id)

    def list_sessions(self):
        return list(self.sessions.values())
